### ISSUE TITLE
What does the "tsdf_max_weight" variable in kinfu.hpp do?

### ISSUE THREAD

**Issue by kokokoharu** [ros-industrial-attic/yak#24]
Hi, I'm new to Kinfu and trying to get myself familiar with it. In "kinfu.hpp" there is a member variable "int tsdf_max_weight" but it seems to be lack of description. Could you please brief me about what it does? Thanks!

**Comment by schornakj** [comment]
Each voxel in the TSDF volume contains 32 bits of data: a half-precision float (16 bits) representing the signed distance to the nearest surface, and an unsigned short integer (16 bits) representing the voxel weight. The weight is essentially the number of times the voxel's distance value has been updated by incoming depth images.

The weight is used when updating voxel distance data. The relevant function can be found in [this library's CUDA code](https://github.com/ros-industrial/yak/blob/9a615cc538d4e1430ee08c22d6ccac183a22198c/yak/src/cuda/tsdf_volume.cu#L102). The new distance value is a weighted average of the voxel's previous distance value and the voxel's distance in the latest depth image. This means that a region of the reconstructed surface that uses data from just a few images will quickly shift if the latest images show that it's shaped differently, while surfaces that have many observations will be less sensitive to changes.

e: To actually answer the question: `tsdf_max_weight` caps the weight value of each voxel. If the max weight is 100, voxels that have been updated 100 times and voxels that have been updated 10000 times will require the same number of new observations at a new distance before the shape of the isosurface begins to change appreciably.

I hope that this clarifies things a little bit!

**Comment by kokokoharu** [comment]
@schornakj Thanks for the helpful reply!
