### ISSUE TITLE
Make OpenCV debug window scalable?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial-attic/yak#28]
The [debug display](https://github.com/ros-industrial/yak/blob/528001095332d55b80fcaed94508201c8cfa232c/yak/src/yak_server.cpp#L10-L11) opened by `yak` is a fixed size window.

For very large depth images, this results in a `2 * width` window which cannot be resized.

**Comment by gavanderhoorn** [comment]
According to various sources, creating the window with the `WINDOW_NORMAL` flag should allow it to be resized.

**Comment by gavanderhoorn** [comment]
@dave992 and @IKapitaniuk FYI.

**Comment by schornakj** [comment]
Closing since #32 implements this.
