### ISSUE TITLE
Marching cubes skips voxels with low weights

### ISSUE THREAD

**Issue by schornakj** [ros-industrial-attic/yak#38]
There's a hard-coded minimum weight value which is used to determine if a voxel should be meshed or not. If a small number of scans are used to create the surface reconstruction, the output mesh could be incomplete or empty.

https://github.com/ros-industrial/yak/blob/ac84aa6807bc998c39a107c04e8a05df66432bc9/yak/src/mc/marching_cubes.cpp#L42-L47

Probably the root cause of [this issue in `yak_ros`](https://github.com/ros-industrial/yak_ros/issues/30).

**Comment by gavanderhoorn** [comment]
Nice!

Well, not so nice it's hard coded, but this confirms a hypothesis we (me and @dave992) formed while trying to debug what was going on.

We hadn't yet made it to `yak` itself.

Thanks for the insight @schornakj.

@dave992: this doesn't mean a proper extrinsic calibration shouldn't be performed :)
