### ISSUE TITLE
Requires PCL 1.9

### ISSUE THREAD

**Issue by DavidMerzJr** [ros-industrial-attic/yak#4]
This package requires PCL 1.9, but this is only mentioned in the CMakeLists.txt file.  It may be nice to include it in the README file when setup instructions are added.

**Comment by schornakj** [comment]
There isn't actually a hard requirement for PCL 1.9 -- it'll work with PCL 1.8 if you modify CMakeLists.txt.

This is fixed in #3 . Does that branch work OK for you?

**Comment by schornakj** [comment]
#5 removed the dependency on PCL 1.9 so I'm going to close this.
