### ISSUE TITLE
Repositories on which this project is based on

### ISSUE THREAD

**Issue by jpizarrom** [ros-industrial-attic/yak#63]
Thanks a lot.

I did not find any link or info about the repositories on which this project is based or where code was taken from.

I would like to know if this project is based or if has been using code from:
- https://github.com/personalrobotics/kinfu_ros
- https://github.com/Nerei/kinfu_remake

Could you list any other projects that yak is based on?

Thanks

PS: I was able to run the demo of https://github.com/ros-industrial/yak_ros2/actions in ROS Foxy.

**Comment by schornakj** [comment]
This project started out as a fork of [`kinfu_ros`](https://github.com/personalrobotics/kinfu_ros), which itself was originally a fork of [`kinfu_remake`](https://github.com/Nerei/kinfu_remake). In particular the CUDA implementations of the TSDF algorithm and the voxel raycasting algorithm are largely unchanged, and I think these libraries go all the way back to the original KinectFusion demo.

`kinfu_ros` and `kinfu_remake` are both licensed under the BSD 3-clause license, which permits commercial use, modification, and distribution. I did notice that `yak` did not preserve the text of the original license, which is one of the conditions listed in the BSD 3-clause license, so we'll need to go add it back in.
