### ISSUE TITLE
TSDF for outdoor large scale maps

### ISSUE THREAD

**Issue by jediofgever** [ros-industrial-attic/yak#64]
Hello, 
This is a question and not a bug report, so please close if unrelated.  I am intending to build large scale outdoor maps and represent them in TSDF by using this repo. I am wondering about the applicability of this. Is there any memory concerns, have anyone tried to do something similar ? , or any suggestions to et started with it ? 
Thank you

**Comment by schornakj** [comment]
Briefly, here are a few challenges I could see:
- The TSDF is represented as a dense voxel volume, so it will be very memory-intensive to capture a large area at high resolution.
- You will need a very accurate estimate for the camera position to mitigate loop closure errors if your camera travels a long distance.
