### ISSUE TITLE
please mention about the dep: cmake_common_scripts

### ISSUE THREAD

**Issue by jediofgever** [ros-industrial-attic/yak#65]
I build this on Ubuntu 20 but there is a dep which I couldn't see being mentioned in readme for build instructions. 

https://github.com/ros-industrial/cmake_common_scripts

Perhaps it will be better to have linked it in readme .

**Comment by schornakj** [comment]
I added an entry to the list of dependencies in the readme in #66.

As a side note, `cmake_common_scripts` is now named `ros_industrial_cmake_boilerplate`.
